# Generated by Django 2.0.3 on 2018-03-31 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('verbose_description', models.TextField(blank=True, null=True)),
                ('is_unique', models.BooleanField()),
                ('formula', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('min_input', models.TextField(blank=True, null=True)),
                ('max_input', models.TextField(blank=True, null=True)),
                ('calc_priority', models.PositiveSmallIntegerField()),
                ('is_updated_in_current_patch', models.BooleanField()),
                ('is_checked_evaluation', models.BooleanField()),
                ('ambiguous_type', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('riot_item_id', models.PositiveIntegerField()),
                ('base_cost', models.PositiveIntegerField()),
                ('total_cost', models.PositiveIntegerField()),
                ('is_purchasable', models.BooleanField()),
                ('sell_gold', models.PositiveIntegerField()),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
                ('from_item_str', models.CharField(blank=True, max_length=200, null=True)),
                ('into_item_str', models.CharField(blank=True, max_length=200, null=True)),
                ('depth', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatchVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_str', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatsBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gold_value_per_amount', models.FloatField()),
                ('patch_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_base_set', to='gold_efficiency.PatchVersion')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('verbose_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='patch_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='gold_efficiency.PatchVersion'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='gold_efficiency.Tag'),
        ),
        migrations.AddField(
            model_name='effect',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_set', to='gold_efficiency.Item'),
        ),
    ]
