# Generated by Django 2.0.3 on 2018-03-20 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('is_evaluable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_item_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('base_cost', models.PositiveIntegerField()),
                ('total_cost', models.PositiveIntegerField()),
                ('is_purchasable', models.BooleanField()),
                ('sell_gold', models.PositiveIntegerField()),
                ('image_json', models.TextField()),
                ('from_item_str', models.CharField(max_length=50, null=True)),
                ('into_item_str', models.CharField(max_length=50, null=True)),
                ('depth', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatchVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_str', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AttackDamage', 'AttackDamage'), ('AbilityPower', 'AbilityPower'), ('Armor', 'Armor'), ('MagicResistance', 'MagicResistance'), ('Health', 'Health'), ('Mana', 'Mana'), ('HealthRegeneration', 'HealthRegeneration'), ('ManaRegeneration', 'ManaRegeneration'), ('CriticalStrikeChance', 'CriticalStrikeChance'), ('AttackSpeed', 'AttackSpeed'), ('FlatMovementSpeed', 'FlatMovementSpeed'), ('LifeSteal', 'LifeSteal'), ('Lethality', 'Lethality'), ('MagicPenetration', 'MagicPenetration'), ('OnhitDamage', 'OnhitDamage'), ('CooldownReduction', 'CooldownReduction'), ('PercentMovementSpeed', 'PercentMovementSpeed'), ('HealAndShieldPower', 'HealAndShieldPower')], max_length=30)),
                ('amount', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_efficiency.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_efficiency.Item')),
            ],
        ),
        migrations.CreateModel(
            name='TagMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('patch_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_efficiency.PatchVersion')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_efficiency.TagMaster'),
        ),
        migrations.AddField(
            model_name='item',
            name='patch_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_efficiency.PatchVersion'),
        ),
        migrations.AddField(
            model_name='effect',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_efficiency.Item'),
        ),
    ]
