# Generated by Django 2.0.3 on 2018-03-27 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('is_unique', models.BooleanField()),
                ('is_evaluable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('riot_item_id', models.PositiveIntegerField()),
                ('base_cost', models.PositiveIntegerField()),
                ('total_cost', models.PositiveIntegerField()),
                ('is_purchasable', models.BooleanField()),
                ('sell_gold', models.PositiveIntegerField()),
                ('img', models.TextField()),
                ('from_item_str', models.CharField(blank=True, max_length=200, null=True)),
                ('into_item_str', models.CharField(blank=True, max_length=200, null=True)),
                ('depth', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatchVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_str', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_efficiency.Item')),
            ],
        ),
        migrations.CreateModel(
            name='StatsBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gold_efficiency_per_amount', models.FloatField()),
                ('patch_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_efficiency.PatchVersion')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GoldPer', 'GoldPer'), ('Damage', 'Damage'), ('Health', 'Health'), ('Stealth', 'Stealth'), ('Consumable', 'Consumable'), ('Mana', 'Mana'), ('Slow', 'Slow'), ('NonbootsMovement', 'NonbootsMovement'), ('MagicPenetration', 'MagicPenetration'), ('Armor', 'Armor'), ('Tenacity', 'Tenacity'), ('Boots', 'Boots'), ('ArmorPenetration', 'ArmorPenetration'), ('Trinket', 'Trinket'), ('Aura', 'Aura'), ('SpellDamage', 'SpellDamage'), ('Vision', 'Vision'), ('Jungle', 'Jungle'), ('LifeSteal', 'LifeSteal'), ('Active', 'Active'), ('HealthRegen', 'HealthRegen'), ('AttackSpeed', 'AttackSpeed'), ('Bilgewater', 'Bilgewater'), ('OnHit', 'OnHit'), ('SpellVamp', 'SpellVamp'), ('SpellBlock', 'SpellBlock'), ('CooldownReduction', 'CooldownReduction'), ('Lane', 'Lane'), ('CriticalStrike', 'CriticalStrike'), ('ManaRegen', 'ManaRegen')], max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_efficiency.Item')),
            ],
        ),
        migrations.AddField(
            model_name='stats',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_efficiency.StatsBase'),
        ),
        migrations.AddField(
            model_name='item',
            name='patch_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gold_efficiency.PatchVersion'),
        ),
        migrations.AddField(
            model_name='effect',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_efficiency.Item'),
        ),
    ]
